//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIES.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid MessageId { get; set; }
        public System.DateTime TimestampUtc { get; set; }
        public string TemplateId { get; set; }
        public string Text { get; set; }
        public int ViewCount { get; set; }
        public int Deaths { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
    }
}
